name: stanslist
description: Stan's List - A modern classifieds platform built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1 
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1 
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  go_router: ^15.1.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.20.2
  url_launcher: ^6.2.4
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/